--- ALTER TABLE  [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] ADD CPF_SOCIO VARCHAR(14);
---- ALTER TABLE  [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] ADD SCORE_EQUIFAX INT;
-- ALTER TABLE  [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] ADD CLI_INADIMPLENTE VARCHAR(1);
-- ALTER TABLE  [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] ADD COD_MAILING VARCHAR(1);


-- 01 - DADOS pj

INSERT INTO [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL]
(
	CNPJ,
	ID_SITUACAO_CADASTRAL,
	COD_NATUREZA_JURIDICA,
	MEI,
	DATA_FUNDACAO,
	SCORE_PJ,
	UF


)


SELECT 
CNPJ,
ID_SITUACAO_CADASTRAL,
ID_NATUREZA_JURIDICA AS COD_NATUREZA_JURIDICA,
MEI,
CONVERT(DATE,LEFT(DATA_FUNDACAO,9)) AS DATA_FUNDACAO,
SCORE_PJ_CUSTOMIZADO AS SCORE_PJ,
UF


From TB_CRDT_BASE_QUOD_FULL_PJ


---- INCLUIR COLUNAS :
--- NOTA: CASO NECESSÁRIO, DESCOMENTE AS COLUNAS



update a

set a.cpf_socio = RIGHT('00000000000000' + documento ,14)
 from [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL]  a 
inner join TB_CRDT_QUOD_BASE_QUADRO_SOCIETARIO b on a.CNPJ  = b.CNPJ
where a.MEI = 's'

--- score sócio
update a
set a.SCORE_EQUIFAX = b.SCORE
FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A 
INNER JOIN TB_CRDT_BASE_EQUIFAX b on A.cpf_socio = b.cpf

---- BUSCAR DÉBITO 
--- DÉBITO CNPJ 
UPDATE A
SET A.CLI_INADIMPLENTE = 'S'
FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A 
INNER JOIN TB_CRDT_BASE_INADIMPLENCIA_LEGADO_NF B ON A.CNPJ = B.CHAVE

---DÉBITO CPF MEI

UPDATE A
SET A.CLI_INADIMPLENTE = 'S'
FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A 
INNER JOIN TB_CRDT_BASE_INADIMPLENCIA_LEGADO_NF B ON A.CPF_SOCIO = B.CHAVE
--- PARTE 02 - REGRAS	
//*
Para regras de cadastro, vamos usar esta base da Quod PJ;
Para regras de score MEI: 
estamos aguardando aprovação para uso do score Equifax (corte TMP = 625 pontos);
Para regras de score NMEI: 
vamos manter o uso score Quod PJ NMEI até a conclusão do backtest (mesmo corte atual).
*/
/*

NMEI: 
Score > 700 - Aprovado
Pode retirar marcações de Corp. Só score e adimplência.
 
MEI
Corte para CC 400 pontos 
Dívida considerada no CPF e no CNPJ
*/

--- INATIVO 
UPDATE A
SET A.COD_MAILING = 'L'
FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A 

WHERE ID_SITUACAO_CADASTRAL <> 'A'

--- DEBITO 
UPDATE A
SET A.COD_MAILING = 'D'
FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A 

WHERE CLI_INADIMPLENTE = 'S' and COD_MAILING is null

--- PRÉ - APROVADO NÃO MEI

UPDATE A

SET A.COD_MAILING = 
	CASe when SCORE_PJ < 700 then 'Q' else 
		CASE WHEN COD_NATUREZA_JURIDICA = '2135' then 'S'
		ELSE 'W' 
	END 
END 
FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A

WHERE MEI = 'N' and cod_mailing is null

-- NEGAR MEI MENOR QUE 90 DIAS ( MEI NOVO)

UPDATE A
SET A.COD_MAILING = 'Q'

FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] A 
INNER JOIN 
(
	SELECT CNPJ FROM
	(
		SELECT 
		CNPJ,
		DATA_FUNDACAO,
		DATEDIFF(D,DATA_FUNDACAO, CAST(GETDATE() AS DATE)) AS TEMPO_FUNDACAO

		FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] WITH(NOLOCK)

		WHERE MEI = 'S' and cod_mailing is null
	) B WHERE TEMPO_FUNDACAO <= 90
) C ON A.CNPJ = C.CNPJ



-- REGRA DE SCORE  para MEI
update a

set a.cod_mailing = b.MAILING_MEI

from [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] a 
inner join 
( 
	SELECT 
	CNPJ,
	CASE WHEN SCORE_EQUIFAX IS  NULL THEN 'Q'
	WHEN SCORE_EQUIFAX < 400  THEN 'Q'
	WHEN SCORE_EQUIFAX BETWEEN 400 AND  624 THEN 'K'
	WHEN SCORE_EQUIFAX  >= 625 THEN 'R'
	END  AS MAILING_MEI

	FROM [TB_CRDT_BASE_MAILNG_PJ_EMPRESARIAL] WITH(NOLOCK)

	WHERE MEI = 'S' and cod_mailing is null
) b on a.cnpj = b.cnpj



